@startuml sd_ModificaPassword
title <b>sd ModificaPassword</b>

actor "Studente" as Studente
boundary "GestioneProfilo" as GestioneProfilo
boundary "FormModificaPassword" as FormModificaPassword
control "GestioneModificaPasswordCtl" as GestioneModificaPasswordCtl
entity "Studente" as EntityStudente
boundary "PannelloErrore" as PannelloErrore
boundary "PannelloAvviso" as PannelloAvviso
boundary "DBMSBoundary" as DBMSBoundary
actor "DBMS" as DBMS

activate Studente
Studente -> GestioneProfilo : 1: ClickModificaPassword()
activate GestioneProfilo
GestioneProfilo -> GestioneModificaPasswordCtl : 1.1: AvviaModificaPassword()
activate GestioneModificaPasswordCtl
GestioneModificaPasswordCtl -> FormModificaPassword : 2: MostraFormModificaPassword()
activate FormModificaPassword
Studente -> FormModificaPassword : 3: InserisciDatiPassword(passwordCorrente, nuovaPassword, confermaNuovaPassword)
Studente -> FormModificaPassword : 4: ClickConferma()
FormModificaPassword -> GestioneModificaPasswordCtl : 4.1: InviaDatiPassword(passwordCorrente, nuovaPassword, confermaNuovaPassword)
GestioneModificaPasswordCtl -> GestioneModificaPasswordCtl : 5.0: nuovaPasswordValida = ValidaNuovaPassword(passwordCorrente, nuovaPassword, confermaNuovaPassword)

alt 5: nuovaPasswordValida = Falso
    GestioneModificaPasswordCtl -> PannelloErrore : 5.1: MostraPannelloErrore("Errore Password")
    activate PannelloErrore
    Studente -> PannelloErrore : 5.2: ClickChiudi()
    PannelloErrore -> PannelloErrore : 5.3: ChiudiPannello()
    destroy PannelloErrore
    GestioneModificaPasswordCtl -> GestioneProfilo : 5.4: MostraGestioneProfilo()
else 6: nuovaPasswordValida = Vero
    GestioneModificaPasswordCtl -> GestioneModificaPasswordCtl : 6.0: CriptaPassword(nuovaPassword)
    GestioneModificaPasswordCtl -> EntityStudente : 6.0.1: SetPassword(passwordCifrata)
    activate EntityStudente
    deactivate EntityStudente
    GestioneModificaPasswordCtl -> DBMSBoundary : 6.1.1: RichiediAggiornamentoPassword(idStudente, passwordCifrata)
    activate DBMSBoundary
    DBMSBoundary -> DBMS : 6.1.2: queryUpdatePassword(idStudente, passwordCifrata)
    activate DBMS
    DBMS --> DBMSBoundary : esitoAggiornamentoPassword
    deactivate DBMS
    DBMSBoundary --> GestioneModificaPasswordCtl : esitoAggiornamentoPassword
    deactivate DBMSBoundary
    GestioneModificaPasswordCtl -> PannelloAvviso : 6.2: MostraPannelloAvviso("Modifica Avvenuta")
    activate PannelloAvviso
    Studente -> PannelloAvviso : 6.3: ClickChiudi()
    PannelloAvviso -> PannelloAvviso : 6.4: ChiudiPannello()
    destroy PannelloAvviso
    GestioneModificaPasswordCtl -> GestioneProfilo : 6.5: MostraGestioneProfilo()
end

deactivate FormModificaPassword
deactivate GestioneModificaPasswordCtl
deactivate GestioneProfilo
deactivate Studente

@enduml
