@startuml sd_RecuperoPassword
title <b>sd RecuperoPassword</b>

actor "Studente" as Studente
boundary "ModuloLogin" as ModuloLogin
boundary "FormRecuperoPassword" as FormRecuperoPassword
control "GestioneRecuperoPasswordCtl" as GestioneRecuperoPasswordCtl
boundary "PannelloErrore" as PannelloErrore
boundary "PannelloAvviso" as PannelloAvviso
boundary "DBMSBoundary" as DBMSBoundary
actor "DBMS" as DBMS

activate Studente
Studente -> ModuloLogin : 1: SelezionaRecuperoPassword()
activate ModuloLogin
ModuloLogin -> GestioneRecuperoPasswordCtl : 1.1: AvviaRecuperoPassword()
deactivate ModuloLogin
activate GestioneRecuperoPasswordCtl
GestioneRecuperoPasswordCtl -> FormRecuperoPassword : 2: MostraFormRecuperoPassword()
activate FormRecuperoPassword
Studente -> FormRecuperoPassword : 3: InserisciEmail(email)
Studente -> FormRecuperoPassword : 4: ClickConferma()
FormRecuperoPassword -> GestioneRecuperoPasswordCtl : 4.1: InviaEmailRecupero(email)
GestioneRecuperoPasswordCtl -> GestioneRecuperoPasswordCtl : 5.0: formatoEmailValido = ValidaFormatoEmail(email)

loop 5: formatoEmailValido = Falso
    GestioneRecuperoPasswordCtl -> PannelloErrore : 5.1: MostraPannelloErrore("E-mail non valida")
    activate PannelloErrore
    Studente -> PannelloErrore : 5.2: ClickChiudi()
    PannelloErrore -> PannelloErrore : 5.3: ChiudiPannello()
    destroy PannelloErrore
    Studente -> FormRecuperoPassword : 5.4: InserisciEmail(email)
    Studente -> FormRecuperoPassword : 5.5: ClickConferma()
    FormRecuperoPassword -> GestioneRecuperoPasswordCtl : 5.5.1: InviaEmailRecupero(email)
    GestioneRecuperoPasswordCtl -> GestioneRecuperoPasswordCtl : 5.5.2: formatoEmailValido = ValidaFormatoEmail(email)
end

GestioneRecuperoPasswordCtl -> DBMSBoundary : 6.1: RichiediVerificaAccountEmail(email)
activate DBMSBoundary
DBMSBoundary -> DBMS : 6.2: querySelectAccountPerEmail(email)
activate DBMS
DBMS --> DBMSBoundary : esitoVerificaEmail
DBMSBoundary --> GestioneRecuperoPasswordCtl : esitoVerificaEmail
Deactivate DBMS
Deactivate DBMSBoundary

alt 7: esitoVerificaEmail = Falso
    GestioneRecuperoPasswordCtl -> PannelloErrore : 7.1: MostraPannelloErrore("Nessun account associato all'indirizzo email inserito")
    activate PannelloErrore
    Studente -> PannelloErrore : 7.2: ClickChiudi()
    PannelloErrore -> PannelloErrore : 7.3: ChiudiPannello()
    destroy PannelloErrore
    GestioneRecuperoPasswordCtl -> FormRecuperoPassword : 7.4: MostraFormRecuperoPassword()
else 8: esitoVerificaEmail = Vero
    GestioneRecuperoPasswordCtl -> GestioneRecuperoPasswordCtl : 8.1: GeneraTokenUnivocoReset()
    GestioneRecuperoPasswordCtl -> DBMSBoundary : 8.2.1: RichiediSalvataggioTokenReset(email, tokenReset)
    activate DBMSBoundary
    DBMSBoundary -> DBMS : 8.2.2: queryInsertTokenReset(email, tokenReset)
    activate DBMS
    DBMS --> DBMSBoundary : esitoSalvataggioToken
    deactivate DBMS
    DBMSBoundary --> GestioneRecuperoPasswordCtl : esitoSalvataggioToken
    deactivate DBMSBoundary
    GestioneRecuperoPasswordCtl -> GestioneRecuperoPasswordCtl : 8.3: InviaEmailLinkReset(email, tokenReset)
    GestioneRecuperoPasswordCtl -> PannelloAvviso : 8.4: MostraPannelloAvviso("Email inviata")
    activate PannelloAvviso
    Studente -> PannelloAvviso : 8.5: ClickChiudi()
    PannelloAvviso -> PannelloAvviso : 8.6: ChiudiPannello()
    destroy PannelloAvviso
    GestioneRecuperoPasswordCtl -> ModuloLogin : 8.7: MostraModuloLogin()
end

deactivate FormRecuperoPassword
deactivate GestioneRecuperoPasswordCtl
deactivate Studente

@enduml
